import Card from '@/components/card';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="mx-auto container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="my-16 flex flex-1 flex-col align-center justify-center">
        <h1 className="text-center text-blue-500">
          Welcome <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-center">
          Get started by editing <code className="">pages/index.js</code>
        </p>

        <div className="flex align-center justify-center flex-wrap">
          <Card
            as="a"
            href="https://nextjs.org/docs"
            className="m-4 p-3 text-left border border-gray-200 round-4 w-1/3">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Card>

          <Card
            as="a"
            href="https://nextjs.org/learn"
            className="m-4 p-3 text-left border border-gray-200 round-4 w-1/3">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Card>

          <Card
            as="a"
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="m-4 p-3 text-left border border-gray-200 round-4 w-1/3">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Card>

          <Card
            as="a"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="m-4 p-3 text-left border border-gray-200 round-4 w-1/3">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </Card>
        </div>
      </main>

      <footer className="flex py-4 border-top border-gray-200 justify-center align-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className="ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
